In [10]:
#資料的準備
import numpy as np
from numpy import random
from numpy import nan as NA
import pandas as pd
random.seed(0)
df = pd.DataFrame(np.random.rand(10, 4))
# 設定為NA
df.iloc[1,0] = NA
df.iloc[2:3,2] = NA
df.iloc[5:,3] = NA
print(df, '\n\n')
df = df.dropna()#將所有NaN的row刪掉
print(df)

          0         1         2         3
0  0.548814  0.715189  0.602763  0.544883
1       NaN  0.645894  0.437587  0.891773
2  0.963663  0.383442       NaN  0.528895
3  0.568045  0.925597  0.071036  0.087129
4  0.020218  0.832620  0.778157  0.870012
5  0.978618  0.799159  0.461479       NaN
6  0.118274  0.639921  0.143353       NaN
7  0.521848  0.414662  0.264556       NaN
8  0.456150  0.568434  0.018790       NaN
9  0.612096  0.616934  0.943748       NaN


          0         1         2         3
0  0.548814  0.715189  0.602763  0.544883
3  0.568045  0.925597  0.071036  0.087129
4  0.020218  0.832620  0.778157  0.870012

In [11]:
#資料的準備
import numpy as np
from numpy import random
from numpy import nan as NA
import pandas as pd
random.seed(0)
df = pd.DataFrame(np.random.rand(10, 4))
# 設定為NA
df.iloc[1,0] = NA
df.iloc[2:3,2] = NA
df.iloc[5:,3] = NA
print(df, '\n\n')
df = df[[0, 1]].dropna()#只取0-1column,並將其中的有NaN的row丟掉
print(df)

          0         1         2         3
0  0.548814  0.715189  0.602763  0.544883
1       NaN  0.645894  0.437587  0.891773
2  0.963663  0.383442       NaN  0.528895
3  0.568045  0.925597  0.071036  0.087129
4  0.020218  0.832620  0.778157  0.870012
5  0.978618  0.799159  0.461479       NaN
6  0.118274  0.639921  0.143353       NaN
7  0.521848  0.414662  0.264556       NaN
8  0.456150  0.568434  0.018790       NaN
9  0.612096  0.616934  0.943748       NaN


          0         1
0  0.548814  0.715189
2  0.963663  0.383442
3  0.568045  0.925597
4  0.020218  0.832620
5  0.978618  0.799159
6  0.118274  0.639921
7  0.521848  0.414662
8  0.456150  0.568434
9  0.612096  0.616934

In [13]:
#資料的準備
import numpy as np
from numpy import random
from numpy import nan as NA
import pandas as pd
random.seed(0)
df = pd.DataFrame(np.random.rand(10, 4))
# 設定為NA
df.iloc[1,0] = NA
df.iloc[2:3,2] = NA
df.iloc[5:,3] = NA
print(df, '\n\n')
df = df.fillna(method = 'ffill')#取前一列的值來填補
print(df)

          0         1         2         3
0  0.548814  0.715189  0.602763  0.544883
1       NaN  0.645894  0.437587  0.891773
2  0.963663  0.383442       NaN  0.528895
3  0.568045  0.925597  0.071036  0.087129
4  0.020218  0.832620  0.778157  0.870012
5  0.978618  0.799159  0.461479       NaN
6  0.118274  0.639921  0.143353       NaN
7  0.521848  0.414662  0.264556       NaN
8  0.456150  0.568434  0.018790       NaN
9  0.612096  0.616934  0.943748       NaN


          0         1         2         3
0  0.548814  0.715189  0.602763  0.544883
1  0.548814  0.645894  0.437587  0.891773
2  0.963663  0.383442  0.437587  0.528895
3  0.568045  0.925597  0.071036  0.087129
4  0.020218  0.832620  0.778157  0.870012
5  0.978618  0.799159  0.461479  0.870012
6  0.118274  0.639921  0.143353  0.870012
7  0.521848  0.414662  0.264556  0.870012
8  0.456150  0.568434  0.018790  0.870012
9  0.612096  0.616934  0.943748  0.870012

In [14]:
#資料的準備
import numpy as np
from numpy import random
from numpy import nan as NA
import pandas as pd
random.seed(0)
df = pd.DataFrame(np.random.rand(10, 4))
# 設定為NA
df.iloc[1,0] = NA
df.iloc[2:3,2] = NA
df.iloc[5:,3] = NA
print(df, '\n\n')
print(df.mean(), '\n\n')
df = df.fillna(df.mean())#取前一列的值來填補
print(df)

          0         1         2         3
0  0.548814  0.715189  0.602763  0.544883
1       NaN  0.645894  0.437587  0.891773
2  0.963663  0.383442       NaN  0.528895
3  0.568045  0.925597  0.071036  0.087129
4  0.020218  0.832620  0.778157  0.870012
5  0.978618  0.799159  0.461479       NaN
6  0.118274  0.639921  0.143353       NaN
7  0.521848  0.414662  0.264556       NaN
8  0.456150  0.568434  0.018790       NaN
9  0.612096  0.616934  0.943748       NaN


0    0.531970
1    0.654185
2    0.413497
3    0.584539
dtype: float64


          0         1         2         3
0  0.548814  0.715189  0.602763  0.544883
1  0.531970  0.645894  0.437587  0.891773
2  0.963663  0.383442  0.413497  0.528895
3  0.568045  0.925597  0.071036  0.087129
4  0.020218  0.832620  0.778157  0.870012
5  0.978618  0.799159  0.461479  0.584539
6  0.118274  0.639921  0.143353  0.584539
7  0.521848  0.414662  0.264556  0.584539
8  0.456150  0.568434  0.018790  0.584539
9  0.612096  0.616934  0.943748  0.584539

In [15]:
#其他fillna可利用?df.fillna來查詢
?df.fillna

Signature:
df.fillna(
    value: 'object | ArrayLike | None' = None,
    method: 'FillnaOptions | None' = None,
    axis: 'Axis | None' = None,
    inplace: 'bool' = False,
    limit=None,
    downcast=None,
) -> 'DataFrame | None'
Docstring:
Fill NA/NaN values using the specified method.

Parameters
----------
value : scalar, dict, Series, or DataFrame
    Value to use to fill holes (e.g. 0), alternately a
    dict/Series/DataFrame of values specifying which value to use for
    each index (for a Series) or column (for a DataFrame).  Values not
    in the dict/Series/DataFrame will not be filled. This value cannot
    be a list.
method : {'backfill', 'bfill', 'pad', 'ffill', None}, default None
    Method to use for filling holes in reindexed Series
    pad / ffill: propagate last valid observation forward to next valid
    backfill / bfill: use next valid observation to fill gap.
axis : {0 or 'index', 1 or 'columns'}
    Axis along which to fill missing values.
inplace : bool, default False
    If True, fill in-place. Note: this will modify any
    other views on this object (e.g., a no-copy slice for a column in a
    DataFrame).
limit : int, default None
    If method is specified, this is the maximum number of consecutive
    NaN values to forward/backward fill. In other words, if there is
    a gap with more than this number of consecutive NaNs, it will only
    be partially filled. If method is not specified, this is the
    maximum number of entries along the entire axis where NaNs will be
    filled. Must be greater than 0 if not None.
downcast : dict, default is None
    A dict of item->dtype of what to downcast if possible,
    or the string 'infer' which will try to downcast to an appropriate
    equal type (e.g. float64 to int64 if possible).

Returns
-------
DataFrame or None
    Object with missing values filled or None if ``inplace=True``.

See Also
--------
interpolate : Fill NaN values using interpolation.
reindex : Conform object to new index.
asfreq : Convert TimeSeries to specified frequency.

Examples
--------
>>> df = pd.DataFrame([[np.nan, 2, np.nan, 0],
...                    [3, 4, np.nan, 1],
...                    [np.nan, np.nan, np.nan, np.nan],
...                    [np.nan, 3, np.nan, 4]],
...                   columns=list("ABCD"))
>>> df
     A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  NaN  NaN NaN  NaN
3  NaN  3.0 NaN  4.0

Replace all NaN elements with 0s.

>>> df.fillna(0)
     A    B    C    D
0  0.0  2.0  0.0  0.0
1  3.0  4.0  0.0  1.0
2  0.0  0.0  0.0  0.0
3  0.0  3.0  0.0  4.0

We can also propagate non-null values forward or backward.

>>> df.fillna(method="ffill")
     A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  3.0  4.0 NaN  1.0
3  3.0  3.0 NaN  4.0

Replace all NaN elements in column 'A', 'B', 'C', and 'D', with 0, 1,
2, and 3 respectively.

>>> values = {"A": 0, "B": 1, "C": 2, "D": 3}
>>> df.fillna(value=values)
     A    B    C    D
0  0.0  2.0  2.0  0.0
1  3.0  4.0  2.0  1.0
2  0.0  1.0  2.0  3.0
3  0.0  3.0  2.0  4.0

Only replace the first NaN element.

>>> df.fillna(value=values, limit=1)
     A    B    C    D
0  0.0  2.0  2.0  0.0
1  3.0  4.0  NaN  1.0
2  NaN  1.0  NaN  3.0
3  NaN  3.0  NaN  4.0

When filling using a DataFrame, replacement happens along
the same column names and same indices

>>> df2 = pd.DataFrame(np.zeros((4, 4)), columns=list("ABCE"))
>>> df.fillna(df2)
     A    B    C    D
0  0.0  2.0  0.0  0.0
1  3.0  4.0  0.0  1.0
2  0.0  0.0  0.0  NaN
3  0.0  3.0  0.0  4.0

Note that column D is not affected since it is not present in df2.
File:      d:\file\anaconda3\envs\lab\lib\site-packages\pandas\core\frame.py
Type:      method